[package]
name = "nisshi-storage-null"
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
include.workspace = true

[dependencies]
async-trait.workspace = true
nisshi-sans-io.workspace = true
nisshi-storage.workspace = true
regex.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[lints]
workspace = true
