{
 "title": "Nisshi",
 "time": { "from": "2026-04-20T15:24:12.913Z", "to": "2026-04-20T15:34:12.913Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Batch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "batch_request_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "batch_response_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batch Produce Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(batch_produce_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Send Queued Records Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(batch_send_queued_records_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Produce Enqueue Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(batch_produce_queued_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Your Ticket Is Ready Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(batch_produce_your_ticket_is_ready_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeout Trigger Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(batch_produce_timeout_expired_trigger_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(batch_ticket_poll_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Wake Event Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(batch_send_queued_wake_event_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validation Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(registry_validation_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "libSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce In Tx Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_produce_in_tx_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_transaction_with_behavior_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "targets": [
      {
       "expr": "rate(nisshi_sqlite_requests_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Engine Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_engine_request_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connect Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_connect_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delegate Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_delegate_request_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transaction Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_sqlite_transaction_commit_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "targets": [
      {
       "expr": "rate(nisshi_sqlite_error[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Permit Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_storage_channel_permit_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(nisshi_storage_channel_request_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "rate(nisshi_storage_channel_error[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Channel Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "targets": [
      {
       "expr": "nisshi_storage_channel_capacity",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Delta Lake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Record Batch Write Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 412 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(deltalake_write_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Record Batch Row Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 412 },
     "targets": [
      {
       "expr": "rate(deltalake_record_batch_rows_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limit Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 420 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(deltalake_rate_limit_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Flush And Commit Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 420 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(deltalake_flush_and_commit_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Files Skipped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 428 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_files_skipped_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Files Considered",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 428 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_considered_files_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Number of Batches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 436 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_num_batches_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Files Added",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 436 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_num_files_added_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 444 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_partitions_optimized_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimize Files Removed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 444 },
     "targets": [
      {
       "expr": "rate(deltalake_optimize_num_files_removed_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Timeout Expired Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 666 },
     "targets": [
      {
       "expr": "rate(batch_timeout_expired_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send Pending Batch Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 666 },
     "targets": [
      {
       "expr": "rate(send_pending_batch_total{job=\"nisshi-proxy\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send Pending Batch Found Owners",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 674 },
     "targets": [
      {
       "expr": "rate(send_pending_found_owner_total{job=\"nisshi-proxy\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send Pending Batch Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 674 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(send_pending_produce_duration_milliseconds_bucket{job=\"nisshi-proxy\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Ticket Ready Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 682 },
     "targets": [
      {
       "expr": "rate(batch_ticket_ready_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Record Overflow Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 682 },
     "targets": [
      {
       "expr": "rate(batch_record_overflow_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send Pending Owner Wake Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 690 },
     "targets": [
      {
       "expr": "rate(send_pending_owner_wake_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Send Pending Empty Batch Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 690 },
     "targets": [
      {
       "expr": "rate(send_pending_empty_batch_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "MinIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "MinIO System Process IO W Char Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "rate(minio_system_process_io_wchar_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MinIO System Process IO R Char Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "rate(minio_system_process_io_rchar_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MinIO Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "rate(minio_api_requests_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MinIO System Drive API Latency Micros",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "targets": [
      {
       "expr": "minio_system_drive_api_latency_micros",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MinIO API Request Traffic Sent Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "rate(minio_api_requests_traffic_sent_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MinIO API Request Traffic Recv Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "expr": "rate(minio_api_requests_traffic_received_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce Request/Response Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 668 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(produce_request_response_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Generate Produce Batch Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 668 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(generate_produce_batch_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Produce Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 676 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(produce_duration_milliseconds_bucket{job=\"nisshi-generator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Receive Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 676 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(tcp_receive_duration_milliseconds_bucket{job=\"nisshi-generator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Connect Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 684 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(tcp_connect_duration_milliseconds_bucket{job=\"nisshi-generator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Record Produce Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 684 },
     "targets": [
      {
       "expr": "sum(rate(produce_record_count_total{job=\"nisshi-generator\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Send Duration Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 692 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(tcp_send_duration_milliseconds_bucket{job=\"nisshi-generator\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate Limit Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 692 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(rate_limit_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "TCP Bytes Sent Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 700 },
     "targets": [
      {
       "expr": "rate(tcp_bytes_sent_total{job=\"nisshi-generator\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Response From Bytes Millis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 700 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(api_response_from_bytes_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "30,000ft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(nisshi_api_requests_total[$__rate_interval])",
       "legendFormat": "{{api_name}}"
      }
     ]
    },
    {
     "title": "API Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(nisshi_request_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Stats",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nisshi_api_requests_total", "legendFormat": "{{api_name}}" }
     ]
    },
    {
     "title": "Consumer Coordinator Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "targets": [
      {
       "expr": "rate(nisshi_group_coordinator_requests_total[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Storage Container Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "rate(nisshi_storage_container_requests_total[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Storage Container",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "nisshi_storage_container_requests_total",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 758 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(nisshi_sql_duration_milliseconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SQL Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 758 },
     "targets": [
      {
       "expr": "rate(nisshi_sql_duration_milliseconds_count[$__rate_interval])",
       "legendFormat": "{{sql}}"
      }
     ]
    }
   ]
  },
  { "title": "Object Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "S3 API Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nisshi_object_store_request_duration_milliseconds_count",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Object Store Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nisshi_object_store_request_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Cache Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(nisshi_objectstore_cache_entries_total[$__rate_interval])",
     "legendFormat": "{{method}}/{{outcome}}"
    }
   ]
  },
  {
   "title": "Metadata Cache Outcome Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(nisshi_objectstore_cache_outcomes_total{method=\"get_opts\"}[$__rate_interval])",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Object Store Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "rate(nisshi_object_store_request_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Object Store Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(nisshi_object_store_request_error_total{method=\"get_opts\"}[$__rate_interval])",
     "legendFormat": "get_opts/{{reason}}"
    },
    {
     "expr": "rate(nisshi_object_store_request_error_total{method=\"put_opts\"}[$__rate_interval])",
     "legendFormat": "put_opts/{{reason}}"
    }
   ]
  },
  {
   "title": "Opticon Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "rate(nisshi_opticon_requests_total[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Opticon Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "rate(nisshi_opticon_errors_total{method=\"with\"}[$__rate_interval])",
     "legendFormat": "with/{{error}}"
    },
    {
     "expr": "rate(nisshi_opticon_errors_total{method=\"with_mut\"}[$__rate_interval])",
     "legendFormat": "with_mut/{{error}}"
    }
   ]
  },
  {
   "title": "Metadata Cache Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "rate(nisshi_objectstore_cache_requests_total[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Metadata Cache Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "rate(nisshi_objectstore_cache_errors_total{method=\"put_opts\"}[$__rate_interval])",
     "legendFormat": "put_opts/{{error}}"
    },
    {
     "expr": "rate(nisshi_objectstore_cache_errors_total{method=\"get_opts\"}[$__rate_interval])",
     "legendFormat": "get_opts/{{error}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "API Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nisshi_request_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nisshi_response_size_bytes_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}